//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRLINE_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIRLINE_DETAILS()
        {
            this.JOURNEY_DETAILS = new HashSet<JOURNEY_DETAILS>();
        }
    
        public int AIRLINEID { get; set; }
        public string AIRLINE { get; set; }
        public string AIRLINECODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNEY_DETAILS> JOURNEY_DETAILS { get; set; }
    }
}
