//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightSearch.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightEntities : DbContext
    {
        public FlightEntities()
            : base("name=FlightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AIRLINE_DETAILS> AIRLINE_DETAILS { get; set; }
        public virtual DbSet<FLIGHT_SERVICE> FLIGHT_SERVICE { get; set; }
        public virtual DbSet<JOURNEY_DETAILS> JOURNEY_DETAILS { get; set; }
        public virtual DbSet<OPERATIONAL_DAY> OPERATIONAL_DAY { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
