//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHT_SERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLIGHT_SERVICE()
        {
            this.JOURNEY_DETAILS = new HashSet<JOURNEY_DETAILS>();
            this.JOURNEY_DETAILS1 = new HashSet<JOURNEY_DETAILS>();
        }
    
        public int FLIGHTSERVICEID { get; set; }
        public string FLIGHTSERVICENAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNEY_DETAILS> JOURNEY_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOURNEY_DETAILS> JOURNEY_DETAILS1 { get; set; }
    }
}
