//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightSearch.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATIONAL_DAY
    {
        public int OPERATIONALDAYID { get; set; }
        public Nullable<int> OPERATIONALDAY { get; set; }
        public int JOURNEYDETAILSID { get; set; }
    
        public virtual JOURNEY_DETAILS JOURNEY_DETAILS { get; set; }
    }
}
